name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install React dependencies
        working-directory: ./cadastro-produto
        run: |
          npm install

      - name: Run React tests
        working-directory: ./cadastro-produto
        run: |
          npm test -- --watchAll=false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask flask-cors pytest Flask-Testing

      - name: Start backend server
        run: |
          python app_principal.py &
          sleep 10 # Tempo para o backend iniciar

      - name: Start React server
        working-directory: ./cadastro-produto
        run: |
          npm start &
          sleep 15 # Tempo para o frontend iniciar

      - name: Run Playwright tests
        working-directory: ./tests
        run: |
          npm install -D playwright
          npx playwright install
          npx playwright test
